### PR TITLE
feature/revert-to-batched-map

### PR DESCRIPTION
**Pull request by donovanr**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [ ] Provide context of changes.
- [x] Provide relevant tests for your feature or bug fix.
- [x] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

### CODE REVIEW

**Comment by donovanr** [comment]
I think we should revert to some batch settings such that the pipeline can actually run on some of our hardware.  Maybe it should be a command-line / kwarg option?  sort of out of my purview, but this version at least ran successfully.

**Review by evamaxfield — APPROVED** [review]

**Comment by evamaxfield** [comment]
> I think we should revert to some batch settings such that the pipeline can actually run on some of our hardware. Maybe it should be a command-line / kwarg option? sort of out of my purview, but this version at least ran successfully.

do you mean on LocalCluster? or on what?

**Comment by donovanr** [comment]
i guess local / distributed could be a kwarg, but I was referring to `batch_size`

**Comment by evamaxfield** [comment]
Local / Distributed is a kwarg already: `--distributed` but the batch size shouldn't actually need to be set. There is a bug somewhere that I haven't fixed, but batch size by default _should_ be the number of workers available to the dask scheduler.

https://github.com/AllenCellModeling/aics_dask_utils/issues/4

**Comment by donovanr** [comment]
i was running into batch size too small = weird time-out failures, batch_size too big = memory crash

**Comment by donovanr** [comment]
we should talk maybe, but cpu-resource-based batch-size may not fit for big file manipulation workloads

**Comment by evamaxfield** [comment]
batch size being too small and erroring is fascinating. That sounds more like SLURM + Isilon failures.

**Comment by evamaxfield** [comment]
@donovanr did you want to merge this?

**Comment by donovanr** [comment]
i guess?  I really want the main branch to be able to run on at least one of our computers.  If it needs work with kwargs, that's fine but I don't have time to do it unfortunately.

**Comment by evamaxfield** [comment]
I will try to add the kwargs for SLURM cluster settings and fix the local cluster as well today

**Comment by evamaxfield** [comment]
@donovanr this now resolves a bunch of stuff.

* kwargs for distributed configuration
* fix local cluster worker count (safety catch really)
* `batch_size` is now computed and passed down to steps

**Pull request merged**
